apply plugin: 'com.android.application'

apply plugin: 'kotlin-android'

apply plugin: 'kotlin-kapt'

android {
    namespace = "com.mejdoo.clean"
    compileSdkVersion 36
    defaultConfig {
        applicationId "com.mejdoo.clean"
        minSdkVersion 21
        targetSdkVersion 36
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    viewBinding {
        enabled = true
    }
    dataBinding {
        enabled = true
    }
    testOptions {
        unitTests.returnDefaultValues = true
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])

    //Kotlin
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"

    //Android X
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'androidx.cardview:cardview:1.0.0'
    implementation 'androidx.recyclerview:recyclerview:1.4.0'
    implementation 'com.google.android.material:material:1.13.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.1'

    //Retrofit
    implementation "com.squareup.retrofit2:retrofit:3.0.0"
    implementation "com.squareup.retrofit2:converter-gson:3.0.0"
    implementation "com.squareup.retrofit2:adapter-rxjava2:3.0.0"

    //Android Architecture Components
    implementation "androidx.lifecycle:lifecycle-extensions:2.2.0"
    kapt "androidx.lifecycle:lifecycle-compiler:2.9.4"
    implementation "androidx.room:room-runtime:2.8.3"
    kapt "androidx.room:room-compiler:2.8.3"
    implementation "androidx.room:room-rxjava2:2.8.3"

    //RxJava
    implementation 'io.reactivex.rxjava2:rxandroid:2.1.1'
    implementation 'io.reactivex.rxjava2:rxjava:2.2.21'
    implementation 'io.reactivex.rxjava2:rxkotlin:2.4.0'

    // Koin (Dependency injection framework for Kotlin)
    implementation "org.koin:koin-android:3.4.2"
    implementation "org.koin:koin-android-viewmodel:3.4.2"

    //Picasso for ImageLoading
    implementation 'com.squareup.picasso:picasso:2.71828'

    //Unit testing
    testImplementation 'junit:junit:4.13.2'
    testImplementation "org.mockito:mockito-core:5.20.4"
    testImplementation "org.mockito:mockito-inline:5.2.0"
    testImplementation "androidx.arch.core:core-testing:2.2.0"

    //UI testing
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.7.0'
    androidTestImplementation 'androidx.test:runner:1.7.0'
    androidTestImplementation 'androidx.test:rules:1.7.0'
}
